### ISSUE TITLE
Source of dist files

### ISSUE THREAD

**Issue by sagudev** [servo/servo-build-deps#1]
What is the source of moztools (MSVC)? Are they extracted from mozilla build?

**Comment by mukilan** [comment]
The moztools-3.2.zip file here on GitHub is just the same one that was being downloaded from servo's S3 bucket originally. I'm not sure how that zip was produced, but based on [this](https://github.com/servo/servo/issues/22212#issuecomment-559165857) it does seem like it was extracted from mozilla build.

Maybe @jdm can confirm.

**Comment by jdm** [comment]
That seems like a likely explanation.

**Comment by sagudev** [comment]
I check and it sure seems like it. After landing https://github.com/servo/mozjs/pull/368 and it's companion in servo I will write manual for creating in and make it from MozillaBuild 4.
